### ISSUE TITLE
Doesn't seem to work on Edge

### ISSUE THREAD

**Issue by soichih** [brain-life/ui-tractview#8]
On Edge, I am seeing a blank (white) page when I open a tract view with afq_output.

I see following under the console log.

```
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
warehouse
HTML1300: Navigation occurred.
warehouse
HTML1527: DOCTYPE expected. Consider adding a valid HTML5 doctype: "<!DOCTYPE html>".
warehouse (1,1)
Warning: KaTeX doesn't work in quirks mode. Make sure your website has a suitable doctype.
katex.js (36,1)
running in production mode
app.fa9e4a55956ecb39797f.js (1,280189)
user [object Object]
app.fa9e4a55956ecb39797f.js (1,280189)
   "user"
   {
      [functions]: ,
      __proto__: { },
      exp: 1505568053.977,
      gids: [ ],
      iat: 1505481654,
      iss: "https://brain-life.org/auth",
      profile: { },
      scopes: { },
      sub: 1
   }

polling finished Service completed successfully
app.fa9e4a55956ecb39797f.js (1,79388)
jQuery.Deferred exception: Unable to get property 'get' of undefined or null reference TypeError: Unable to get property 'get' of undefined or null reference
   at Anonymous function (https://brain-life.org/ui/tractview/js/main.js:24:9)
   at j (https://brain-life.org/ui/tractview/node_modules/jquery/dist/jquery.min.js:2:29992)
   at Anonymous function (https://brain-life.org/ui/tractview/node_modules/jquery/dist/jquery.min.js:2:30313) undefined
jquery.min.js (2,31523)
SCRIPT5007: Unable to get property 'get' of undefined or null reference
jquery.min.js (2,31689)

```

This is from a private dataset 
> https://brain-life.org/warehouse/#/dataset/596f8f4605de61002ef3cf8a

**Comment by stevengeeky** [comment]
Seems to work fine on Edge for me, maybe a Windows Update either breaks or fixes it?
Works on the latest version of every modern browser. Interestingly, Firefox has the quickest canvas rendering
